config/routes.rb
Rails.application.routes.draw do
  get 'city/show'
  resources :gossip do
  	resources :comment
  end
  resources :author
  resources :welcome, only: [:index, :show]
  resources :contact, only: [:index]
  resources :team, only: [:index]
  resources :city, except: [:destroy] 
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
	validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
	validates :content, presence: true
	validates :user_id, presence: true
	validates :gossip_id, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
	has_many :join_gossip_tags
	has_many :tags, through: :join_gossip_tags
	has_many :comments
	validates :title, presence: true
	validates :content, presence: true
	validates :user_id, presence: true
end

app/models/join_gossip_tag.rb
class JoinGossipTag < ApplicationRecord
	belongs_to :tag
	belongs_to :gossip

end

app/models/join_pm_recipient.rb
class JoinPmRecipient < ApplicationRecord
	belongs_to :private_message
	belongs_to :user
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :user
	has_many :join_pm_recipients
	validates :content, presence: true
	validates :user_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :join_gossip_tags
	has_many :gossips, through: :join_gossip_tags
	has_many :users, through: :gossips
	validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :city
	has_many :gossips
	has_many :comments
	has_many :tags, through: :gossips
	has_many :private_messages
  	has_many :join_pm_recipients
  	validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "you need a valid email adress please" }
  	validates :first_name, presence: true
  	validates :last_name, presence: true
		validates :password, presence: true, length: { minimum: 6 }

		has_secure_password
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
    def new
  	User.new
  end
  def create
  	User.create
  end

  def show
    @user=User.find(params[:id])
    @gossips=Gossip.where(user_id:params[:id])
  end

  def index
    @users=User.all
  end

  def edit
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
  end

  def update
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
  end

  def destroy
  end
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def show
  	@city=City.find(params[:id])
  	@gossips=Gossip.where(user_id:@city.users.ids)
  end
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
	def new
	  	Comment.new
	end
  def create
  	@gossip=Gossip.find(params[:gossip_id])
    @comment=@gossip.comments.new(content: params[:comment_content], user_id: User.all.sample.id, gossip_id: params[:gossip_id])
  	@user=User.find(@gossip.user_id)
  	@comments=@gossip.comments
  	if @comment.save
      redirect_to gossip_path(@gossip.id)
    else
      redirect_to gossip_path(@gossip.id)
    end
  end

  def show
    @comment=Comment.where(gossip_id: :gossip_id, id: params[:id])
  end

  def index
    @comments=Comment.where(gossip_id: :gossip_id)
  end

  def edit
    @gossip=Gossip.find(params[:gossip_id])
    @comment = @gossip.comments.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:gossip_id])
    @comment = @gossip.comments.find(params[:id])
    if @comment.update(content: params[:comment_content])
      redirect_to gossip_path(@gossip)
    else
      render :edit
    end
  end
  def destroy
    @gossip = Gossip.find(params[:gossip_id])
	@comment = @gossip.comments.find(params[:id])
  	@comment.destroy
    redirect_to gossip_path(@gossip)
  end

end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def new
  	Gossip.new
  end
  def create
    anonymous=User.new(first_name:"Anonymous", last_name:"unknown",age: 99,description: "unknown",email:"unknown#{rand(1000)}@mail.com",city_id:City.all.sample.id)
    anonymous.save
  	@gossip=Gossip.new(title: params[:gossip_title], content: params[:gossip_content], user_id: anonymous.id)
    if @gossip.save
      @gossips=Gossip.all
      render 'index'
    else
      anonymous.destroy
      render 'new'
    end
  end

  def show
    @gossip=Gossip.find(params[:id])
    @user=User.find(@gossip.user_id)
    @comments=@gossip.comments
  end

  def index
    @gossips=Gossip.all
  end

  def edit
    @gossip=Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(title: params[:gossip_title], content: params[:gossip_content])
      redirect_to @gossip
    else
      render :edit
    end
  end
  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    @gossips=Gossip.all
    render 'gossip/index'
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
    def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
   def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end
   def logged_in?
    session[:user_id]
  end
  def authenticate_user
  	unless current_user
	  redirect_to new_session_path
	end
  end
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
	def right_user
	    @gossip=Gossip.find(params[:gossip_id])
	    @comment = @gossip.comments.find(params[:id])
  		unless current_user.id == @comment.user_id
			redirect_to gossip_path(params[:gossip_id])
	  	end
	end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/city/show.html.erb
<div class="card">
  <div class="card-header font-weight-bold">
    City #<%=params[:id]%>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= @city.name%></h5>
    <div class="card-text">
		<p>ZIP Code : <%= @city.zip_code%></p>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-header mb-3">
    <% if @gossips.size == 0 %>
    <p> Il n'y a pas encore de gossip pour <%= @city.name%></p>
    <% else %>
    <p>Voici le(s) <%=@gossips.size%> gossip(s) écrit(s) à <%= @city.name%>:</p>
    <%end%>
   </div>
<div class="card-deck">
<%@gossips.each do |gossip|%>
<div class="col-sm-4 mb-3">
<div class="card">
  <div class="card-header">
    Gossip #<%=gossip.id%>
  </div>
  <div class="card-body align-center">
    <blockquote class="blockquote mb-0">
      <p><%=gossip.title%></p>
    </blockquote>
    <footer class="blockquote-footer">
      <div class="row justify-content-between align-self-center mx-3">
        <p><%= link_to "#{User.find(gossip.user_id).first_name} #{User.find(gossip.user_id).last_name}", author_path(gossip.user_id), :class =>"text-muted p-0"%></p>
        <a class="btn btn-dark" <%= link_to "Voir", gossip_path(gossip.id)%></a>
      </div>
    </footer>
  </div>
</div>
</div>
<%end%>
</div>
</div>

app/views/comment/edit.html.erb
<html>
<div class="card text-center mb-3">
  <div class="card-body">
  <body>
  <% if @comment !=nil%>
  <div class="card bg-light text-danger">
      <% @comment.errors.each do |attr, msg|  %>
      <%= attr %> <%= msg %>
    <% end %>
  </div>
  <% end %>
    <div class="container">
      <h1> Corrige ce commentaire !</h1>
      <%= form_tag gossip_comment_path(@gossip.id,@comment.id), action: 'update', method: "patch" do %>
        <input type="hidden" name="authenticity_token" value= <%= form_authenticity_token %> >
        <div class="row justify-content-center align-self-center mx-5">
          <div class="col-3">
            <%= label_tag 'Commentaire' %>
          </div>
          <div class="col-3">
            <%= text_field_tag 'comment_content', value = @comment.content, options = {style:"height:120px;width:300px;vertical-align:text-top"}%>
          </div>
        </div>
        <%= submit_tag "Valider", class: 'btn btn-dark btn-lg btn-submit'  %>
      <% end %>
    </div>
  </body>
</div>
  </div>
</html>

app/views/gossip/edit.html.erb
<html>
<div class="card text-center mb-3">
  <div class="card-body">
  <body>
  <% if @gossip !=nil%>
  <div class="card bg-light text-danger">
      <% @gossip.errors.each do |attr, msg|  %>
      <%= attr %> <%= msg %>
    <% end %>
  </div>
  <% end %>
    <div class="container">
      <h1> Corrige ce potin !</h1>
      <%= form_tag url_for(action: 'update'), method: "patch" do %>
        <input type="hidden" name="authenticity_token" value= <%= form_authenticity_token %> >
        <br />
        <div class="row justify-content-center align-self-center mx-5">
          <div class="col-3">
          <%= label_tag 'Le titre' %>
          </div>
          <div class="col-3">
          <%= text_field_tag 'gossip_title', value = @gossip.title, options = {style:"height:30px;width:300px"} %>
          </div>
        </div>     
        <br />
        <div class="row justify-content-center align-self-center mx-5">
          <div class="col-3">
            <%= label_tag 'Dis nous tout' %>
          </div>
          <div class="col-3">
            <%= text_field_tag 'gossip_content', value = @gossip.content, options = {style:"height:120px;width:300px;vertical-align:text-top"}%>
          </div>
        </div>
        <br />
        <%= submit_tag "Valider", class: 'btn btn-dark btn-lg btn-submit'  %>
      <% end %>
    </div>
  </body>
</div>
  </div>
</html>

app/views/gossip/index.html.erb
<div class="card text-center mb-3">
  <div class="card-body">
  <% if @gossip !=nil%>
  <div class="card bg-light text-dark font-weight-bold mb-3">
      <%= "Votre modification a bien été enregistrée" %>
  </div>
  <%end%>
  <a class="btn btn-dark" <%= link_to "Soumettre un Gossip", new_gossip_path%></a>
  </div>
</div>
<section>
<div class="card-deck">
<%@gossips.each do |gossip|%>
<div class="col-sm-4 mb-3">
<div class="card">
  <div class="card-header">
    Gossip #<%=gossip.id%>
  </div>
  <div class="card-body align-center">
    <blockquote class="blockquote mb-0">
      <p><%=gossip.title%></p>
    </blockquote>
    <footer class="blockquote-footer">
      <div class="row justify-content-between align-self-center mx-3">
      <div class="row justify-content-between align-self-center mx-3">
        <p><%= link_to "#{User.find(gossip.user_id).first_name} #{User.find(gossip.user_id).last_name}", author_path(gossip.user_id), :class =>"text-muted p-0"%></p>
      </div>
      <div class="row justify-content-between align-self-center">
        <a class="btn btn-dark mr-2" <%= link_to "Voir", gossip_path(gossip.id)%></a>
        <button type="button" class="btn btn-light border-dark">
          # <span class="badge badge-dark"><%=gossip.comments.size%></span>
        </button>
      </div>
      </div>
    </footer>
  </div>
</div>
</div>
<%end%>
</div>
</section>

app/views/gossip/new.html.erb
<html>
<div class="card text-center mb-3">
  <div class="card-body">
  <body>
  <% if @gossip !=nil%>
  <div class="card bg-light text-danger">
      <% @gossip.errors.each do |attr, msg|  %>
      <%= attr %> <%= msg %>
    <% end %>
  </div>
  <% end %>
    <div class="container">
      <h1> Soumets ton potin !</h1>
      <%= form_tag url_for(action: 'create'), method: "post" do %>
        <input type="hidden" name="authenticity_token" value= <%= form_authenticity_token %> >
        <br />
        <div class="row justify-content-center align-self-center mx-5">
          <div class="col-3">
          <%= label_tag 'Le titre' %>
          </div>
          <div class="col-3">
          <%= text_field_tag 'gossip_title', value = nil, options = {style:"height:30px;width:300px"} %>
          </div>
        </div>     
        <br />
        <div class="row justify-content-center align-self-center mx-5">
          <div class="col-3">
            <%= label_tag 'Dis nous tout' %>
          </div>
          <div class="col-3">
            <%= text_field_tag 'gossip_content', value = nil, options = {style:"height:120px;width:300px;vertical-align:text-top"}%>
          </div>
        </div>
        <br />
        <%= submit_tag "Valider", class: 'btn btn-dark btn-lg btn-submit'  %>
      <% end %>
    </div>
  </body>
</div>
  </div>
</html>

app/views/gossip/show.html.erb
<div class="card">
  <div class="card-header">
    <div class="font-weight-bold">Gossip #<%=@gossip.id%></div>
    <div class="text-muted"><%@gossip.tags.each do |item| %> 
    	#<%=item.title%>
    	<%end%>
    	</div>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= @gossip.title%></h5>
    <p class="card-text"><%= @gossip.content%></p>
    <div class="row justify-content-between align-self-center mx-3">
      <div>
        <a hclass="btn btn-dark"<%= link_to "#{@user.first_name} #{@user.last_name}", author_path(@gossip.user_id.to_i), :class =>"text-dark p-0"%></a>
        <div class="text-muted"><%= link_to "#{@user.city.name}", city_path(@user.city.id), :class =>"text-muted p-0"%></div>
      </div>
      <div class="row justify-content-between align-self-center mx-3">
        <a class="btn btn-dark mx-3" <%= link_to "Editer", edit_gossip_path(@gossip.id)%></a>
        <%= form_tag gossip_path(@gossip.id), method: "delete" do %>
          <%= submit_tag "Supprimer", class: 'btn btn-dark btn-submit'%>
        <% end %>
      </div>
    </div>
  </div>
    <div class="card-header mb-3">
    <div class="font-weight-bold"> Commentaires :</div>
   </div>
<div class="card-body">
  <%= form_tag gossip_comment_index_path(@gossip.id), method: "post" do %>
        <input type="hidden" name="authenticity_token" value= <%= form_authenticity_token %> >
        <input type="hidden" name="gossip_id" value= @gossip.id >     
        <br />
        <div class="row justify-content-between align-self-start mx-5">
        <div class="col-4">
          <div class="row justify-content-between align-self-center mx-5">
            <div class="col-3">
              <%= label_tag 'Ajouter un commentaire' %>
            </div>
            <div class="col-3">
              <%= text_field_tag 'comment_content', value = nil, options = {style:"height:120px;width:300px;vertical-align:text-top"}%>
            </div>
          </div>
        </div>
        <div class="col-4">
          <%= submit_tag "Valider", class: 'btn btn-dark btn-lg btn-submit'  %>
        </div></div>
      <% end %>
</div>
<div class="card">
  <div class="card-header mb-3">
    <% if @comments.size == 0 %>
      <p> Il n'y a pas encore de commentaire pour le Gossip #<%= @gossip.id%></p>
    <% else %>
      <p> Il y a <%=@comments.size%> commentaires pour le Gossip #<%= @gossip.id%></p>
    <%end%>
  </div>
<div class="card-deck">
<%n=0%>
<%@comments.each do |comment|%>
<%n+=1%>
<div class="col-sm-4 mb-3">
<div class="card">
  <div class="card-header bg-dark text-white">
    Comment #<%=n%>
  </div>
  <div class="card-body align-center">
    <blockquote class="blockquote mb-0">
      <p><%=comment.content%></p>
    </blockquote>
    <footer class="blockquote-footer">
    <div class="row justify-content-between align-items-center mx-3">
      <div class="row justify-content-between align-self-center mx-3">
        <p><%= link_to "#{User.find(comment.user_id).first_name} #{User.find(comment.user_id).last_name}", author_path(comment.user_id), :class =>"text-muted p-0"%></p>
      </div>
      <div class="row justify-content-between align-self-center">
        <a class="btn btn-light text-muted mr-2" <%= link_to "Editer", edit_gossip_comment_path(@gossip.id,comment.id)%></a>
        <%= form_tag gossip_comment_path(@gossip.id,comment.id), method: "delete" do %>
          <%= submit_tag "Supprimer", class: 'btn btn-light text-muted btn-submit'%>
        <% end %>
      </div>
    </div>
    </footer>
  </div>
</div>
</div>
<%end%>
</div>
</div>


</div>