config/routes.rb
Rails.application.routes.draw do
  get 'city/show'
  resources :gossip do
  	resources :comment
  end
  resources :author
  resources :welcome, only: [:index, :show]
  resources :contact, only: [:index]
  resources :team, only: [:index]
  resources :city, except: [:destroy] 
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
	validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
	validates :content, presence: true
	validates :user_id, presence: true
	validates :gossip_id, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
	has_many :join_gossip_tags
	has_many :tags, through: :join_gossip_tags
	has_many :comments
	validates :title, presence: true
	validates :content, presence: true
	validates :user_id, presence: true
end

app/models/join_gossip_tag.rb
class JoinGossipTag < ApplicationRecord
	belongs_to :tag
	belongs_to :gossip

end

app/models/join_pm_recipient.rb
class JoinPmRecipient < ApplicationRecord
	belongs_to :private_message
	belongs_to :user
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :user
	has_many :join_pm_recipients
	validates :content, presence: true
	validates :user_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :join_gossip_tags
	has_many :gossips, through: :join_gossip_tags
	has_many :users, through: :gossips
	validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :city
	has_many :gossips
	has_many :comments
	has_many :tags, through: :gossips
	has_many :private_messages
  	has_many :join_pm_recipients
  	validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "you need a valid email adress please" }
  	validates :first_name, presence: true
  	validates :last_name, presence: true
		validates :password, presence: true, length: { minimum: 6 }

		has_secure_password
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def show
  	@city=City.find(params[:id])
  	@gossips=Gossip.where(user_id:@city.users.ids)
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
    def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
   def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end
   def logged_in?
    session[:user_id]
  end
  def authenticate_user
  	unless current_user
	  redirect_to new_session_path
	end
  end
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
	def right_user
	    @gossip=Gossip.find(params[:gossip_id])
	    @comment = @gossip.comments.find(params[:id])
  		unless current_user.id == @comment.user_id
			redirect_to gossip_path(params[:gossip_id])
	  	end
	end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


    <title>TGP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
<nav class="navbar navbar-expand-lg navbar-light text-light bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand text-white" <%= link_to "The Gossip Project", welcome_index_path%></a>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link text-light" <%= link_to "Team", team_index_path%></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-light" <%= link_to "Contact", contact_index_path%></a>
      </li>
      <%if logged_in? %>
      <li class="nav-item">
        <a class="nav-link text-light" <%= link_to "Participe, et créé un Gossip", new_gossip_path%></a>
      </li>
      <%end%>
    </ul>
  </div>


  <%if logged_in? %>
  <div class="dropdown mr-5">
    <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <%=current_user.first_name%>
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <a class="dropdown-item badge badge-pill badge-info" <%= link_to "Profil", author_path(current_user.id)%></a>
      <a class="dropdown-item badge badge-pill badge-danger" <%= link_to "Déconnection", session_path(session.id), method: :delete %>
      </div>
    </div>

    <%else%>
    <div class="dropdown mr-5">
      <button class="btn btn-danger dropdown-toggle " type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Inscription / Connection
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item badge badge-pill badge-primary" <%= link_to "S'inscrire", new_author_path%></a>
        <a class="dropdown-item badge badge-pill badge-success" <%= link_to "Se connecter", new_author_path%></a>
      </div>
    </div>
    <%end%>

</nav>
  </header>
  <body>

    <%= yield %>
  </body>
</html>